### ISSUE TITLE
Handle KeyboardInterrupt nicely

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/zalando-kubectl#2]
`CTRL+C` should not lead to stacktraces for the user.

```
$ zalando-kubectl proxy
Starting to serve on 127.0.0.1:8001^CTraceback (most recent call last):
  File "/usr/local/bin/zalando-kubectl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/zalando_kubectl/main.py", line 103, in main
    proxy()
  File "/usr/local/lib/python3.5/dist-packages/zalando_kubectl/main.py", line 76, in proxy
    subprocess.call([kubectl] + sys.argv[1:])
  File "/usr/lib/python3.5/subprocess.py", line 559, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1658, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1608, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by hjacobs** [comment]
This was fixed in https://github.com/zalando-incubator/zalando-kubectl/releases/tag/0.3
